# Generated by Django 3.0.6 on 2020-06-01 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_suborder'),
    ]

    operations = [
        migrations.AddField(
            model_name='suborder',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suborder', to='orders.Customer'),
        ),
    ]
