# Generated by Django 3.0.6 on 2020-06-01 19:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0004_suborder_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suborder',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suborder', to=settings.AUTH_USER_MODEL),
        ),
    ]
