# Generated by Django 3.0.6 on 2020-06-01 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20200601_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='suborder',
            name='category',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
