# Generated by Django 3.0.6 on 2020-06-02 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_suborder_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='PizzaToppings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64)),
                ('size', models.CharField(blank=True, max_length=64)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ntoppings', models.IntegerField()),
                ('toppings', models.ManyToManyField(blank=True, to='orders.PizzaToppings')),
            ],
        ),
    ]
