# Generated by Django 3.0.6 on 2020-06-02 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_pizza_pizzatoppings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PizzaToppings',
            new_name='PizzaTopping',
        ),
    ]
