# Generated by Django 3.0.6 on 2020-06-03 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20200602_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='ptype',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
