# Generated by Django 3.0.6 on 2020-06-03 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_pizza_ptype'),
    ]

    operations = [
        migrations.AddField(
            model_name='suborder',
            name='ntoppings',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='suborder',
            name='ptoppings',
            field=models.ManyToManyField(blank=True, to='orders.PizzaTopping'),
        ),
        migrations.AddField(
            model_name='suborder',
            name='ptype',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
