# Generated by Django 3.0.6 on 2020-06-03 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20200603_1222'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizza',
            old_name='toppings',
            new_name='ptoppings',
        ),
    ]
